name: PuzzleBuilder
main: com.panzegoria.puzzleBuilder.PuzzleBuilderPlugin
version: .01 Dev
commands:
   hint:
      description: This is a demo command.
      usage: /<command>
   BlueprintEnable:
      description: Starts your blueprinting session
      usage: /BlueprintEnable
   BlueprintDisable:
      description: Stops your blueprinting session
      usage: /BlueprintEnable
   Rotate:
      description: Rotates Build Direction 90 Degrees Clockwise
      usage: /Rotate
   Save:
      description: Saves map to disk.
      usage: /Save

