name: Blueprint
main: BlueprintPlugin
version: .04 Dev
commands:
   hint:
      description: This is a demo command.
      usage: /<command>
   BPEnable:
      description: Starts your blueprinting session
      usage: /BPEnable
   BPDisable:
      description: Stops your blueprinting session
      usage: /BPDisable
   BlueprintState:
      description: Gets information about your current blueprint session
      usage: /BlueprintState
   Rotate:
      description: Rotates Build Direction 90 Degrees Clockwise
      usage: /Rotate
